kafka_cluster:
  image: ches/kafka:0.8.2.1
  environment:
    - KAFKA_ADVERTISED_HOST_NAME=marketwatcher.tech
    - KAFKA_ADVERTISED_PORT=9092
    - ZOOKEEPER_IP=zookeeper
  links:
    - "zookeeper"
  ports:
    - "9092:9092"
    - "7203:7203"

zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181:2181"
